language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install coveralls --use-mirrors
script:
    - python manage.py test some_app --settings=test_project.test_settings
    - python manage.py test other_app --settings=test_project.test_settings
    - coverage run --source=some_app manage.py test
after_success:
    - coveralls
